import { Content } from "@/lib/types/content";

// Mock data for testing when TMDB API isn't working
export const MOCK_MOVIES: Content[] = [
    {
        id: "mock-1",
        title: "The Dark Knight",
        description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
        poster: "https://image.tmdb.org/t/p/w342/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        backdrop: "https://image.tmdb.org/t/p/w780/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
        rating: 9.0,
        releaseDate: "2008-07-18",
        type: "movie",
        genres: ["Action", "Crime", "Drama"],
        status: "completed",
        isAdult: false,
        seasonsList: [],
        cast: [],
        recommendations: [],
        trailer: undefined,
    },
    {
        id: "mock-2",
        title: "Inception",
        description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea.",
        poster: "https://image.tmdb.org/t/p/w342/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
        backdrop: "https://image.tmdb.org/t/p/w780/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
        rating: 8.8,
        releaseDate: "2010-07-16",
        type: "movie",
        genres: ["Action", "Sci-Fi", "Thriller"],
        status: "completed",
        isAdult: false,
        seasonsList: [],
        cast: [],
        recommendations: [],
        trailer: undefined,
    },
    {
        id: "mock-3",
        title: "Interstellar",
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        poster: "https://image.tmdb.org/t/p/w342/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        backdrop: "https://image.tmdb.org/t/p/w780/pbrkL804c8yAv3zBZR4QPEafpAR.jpg",
        rating: 8.6,
        releaseDate: "2014-11-07",
        type: "movie",
        genres: ["Adventure", "Drama", "Sci-Fi"],
        status: "completed",
        isAdult: false,
        seasonsList: [],
        cast: [],
        recommendations: [],
        trailer: undefined,
    },
    {
        id: "mock-4",
        title: "The Matrix",
        description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        poster: "https://image.tmdb.org/t/p/w342/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
        backdrop: "https://image.tmdb.org/t/p/w780/icmmSD4vTTDKOq2vvdulafOGw93.jpg",
        rating: 8.7,
        releaseDate: "1999-03-31",
        type: "movie",
        genres: ["Action", "Sci-Fi"],
        status: "completed",
        isAdult: false,
        seasonsList: [],
        cast: [],
        recommendations: [],
        trailer: undefined,
    },
    {
        id: "mock-5",
        title: "Pulp Fiction",
        description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
        poster: "https://image.tmdb.org/t/p/w342/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        backdrop: "https://image.tmdb.org/t/p/w780/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
        rating: 8.9,
        releaseDate: "1994-10-14",
        type: "movie",
        genres: ["Crime", "Drama"],
        status: "completed",
        isAdult: false,
        seasonsList: [],
        cast: [],
        recommendations: [],
        trailer: undefined,
    },
];

export const MOCK_TV_SHOWS: Content[] = [
    {
        id: "mock-tv-1",
        title: "Breaking Bad",
        description: "A high school chemistry teacher turned methamphetamine producer partners with a former student.",
        poster: "https://image.tmdb.org/t/p/w342/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
        backdrop: "https://image.tmdb.org/t/p/w780/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
        rating: 9.5,
        releaseDate: "2008-01-20",
        type: "tv",
        genres: ["Crime", "Drama", "Thriller"],
        status: "completed",
        isAdult: false,
        seasonsList: [],
        cast: [],
        recommendations: [],
        trailer: undefined,
    },
    {
        id: "mock-tv-2",
        title: "Stranger Things",
        description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces.",
        poster: "https://image.tmdb.org/t/p/w342/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        backdrop: "https://image.tmdb.org/t/p/w780/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
        rating: 8.7,
        releaseDate: "2016-07-15",
        type: "tv",
        genres: ["Drama", "Fantasy", "Horror"],
        status: "ongoing",
        isAdult: false,
        seasonsList: [],
        cast: [],
        recommendations: [],
        trailer: undefined,
    },
    {
        id: "mock-tv-3",
        title: "The Last of Us",
        description: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl.",
        poster: "https://image.tmdb.org/t/p/w342/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
        backdrop: "https://image.tmdb.org/t/p/w780/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
        rating: 8.8,
        releaseDate: "2023-01-15",
        type: "tv",
        genres: ["Action", "Adventure", "Drama"],
        status: "ongoing",
        isAdult: false,
        seasonsList: [],
        cast: [],
        recommendations: [],
        trailer: undefined,
    },
];

// Generate more mock data by duplicating
export const generateMockContent = (count: number = 20): Content[] => {
    const allMock = [...MOCK_MOVIES, ...MOCK_TV_SHOWS];
    const result: Content[] = [];
    
    for (let i = 0; i < count; i++) {
        const template = allMock[i % allMock.length];
        result.push({
            ...template,
            id: `mock-${i}`,
            title: `${template.title} ${i + 1}`,
        });
    }
    
    return result;
};
